graph TD;
    A[TOTAL] -->|ENERO| B(MES);
    A -->|ANGELES| C(BASICO);
    A -->|DEPORTIVO| D;
    A -->|MODAFRESCA| E;
    A -->|URBANO| F;
    A -->|BOGOTA| G;
    A -->|INTIMA| H;
    A -->|ESPECIALES| I;
    A -->|PRONTAMODA| J;
    A -->|TOTAL| K;
    A -->|HABILES| L;

    B -->|14483| M(ENERO);
    C -->|22931| N(BASICO);
    D -->|10862| O(DEPORTIVO);
    E -->|24138| P(MODAFRESCA);
    F -->|12069| Q(URBANO);
    G -->|8448| R(BOGOTA);
    H -->|15689| S(INTIMA);
    I -->|8448| T(ESPECIALES);
    J -->|3621| U(PRONTAMODA);
    K -->|120689| V(TOTAL);
    L -->|21| W(HABILES);

    M -->|21| X(ENERO);
    N -->|20| Y(BASICO);
    O -->|20| Z(DEPORTIVO);
    P -->|20| AA(MODAFRESCA);
    Q -->|21| AB(URBANO);
    R -->|23| AC(BOGOTA);
    S -->|20| AD(INTIMA);
    T -->|22| AE(ESPECIALES);
    U -->|19| AF(PRONTAMODA);
    V -->|245| AG(TOTAL);
    W -->| | AH(HABILES);

    X -->|21| AI(ENERO);
    Y -->|20| AJ(BASICO);
    Z -->|20| AK(DEPORTIVO);
    AA -->|20| AL(MODAFRESCA);
    AB -->|21| AM(URBANO);
    AC -->|23| AN(BOGOTA);
    AD -->|20| AO(INTIMA);
    AE -->|22| AP(ESPECIALES);
    AF -->|18| AQ(PRONTAMODA);
    AG -->| | AR(TOTAL);
    AH -->|21| AS(HABILES);

    AI -->|21| AT(ENERO);
    AJ -->|20| AU(BASICO);
    AK -->|20| AV(DEPORTIVO);
    AL -->|20| AW(MODAFRESCA);
    AM -->|21| AX(URBANO);
    AN -->|23| AY(BOGOTA);
    AO -->|20| AZ(INTIMA);
    AP -->|22| BA(ESPECIALES);
    AQ -->|18| BB(PRONTAMODA);
    AR -->| | BC(TOTAL);
    AS -->|21| BD(HABILES);

    AT -->|21| BE(ENERO);
    AU -->|20| BF(BASICO);
    AV -->|20| BG(DEPORTIVO);
    AW -->|20| BH(MODAFRESCA);
    AX -->|21| BI(URBANO);
    AY -->|23| BJ(BOGOTA);
    AZ -->|20| BK(INTIMA);
    BA -->|22| BL(ESPECIALES);
    BB -->|18| BM(PRONTAMODA);
    BC -->| | BN(TOTAL);
    BD -->|21| BO(HABILES);

    BE -->|21| BP(ENERO);
    BF -->|20| BQ(BASICO);
    BG -->|20| BR(DEPORTIVO);
    BH -->|20| BS(MODAFRESCA);
    BI -->|21| BT(URBANO);
    BJ -->|23| BU(BOGOTA);
    BK -->|20| BV(INTIMA);
    BL -->|22| BW(ESPECIALES);
    BM -->|18| BX(PRONTAMODA);
    BN -->| | BY(TOTAL);
    BO -->|21| BZ(HABILES);
